# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=bookstore-secret-key-very-long-and-secure-2024-bookstore-app
app.jwt.expiration=86400000

# Mail (Gmail SMTP - thay bằng email thực)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhcanh9105@gmail.com
spring.mail.password=qtxfgttswvppwyiu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.bookstore=DEBUG
